"""Index `dataset/formated_rag_data/*.json` into pgvector.

Parent-document retrieval: only challenge METADATA (name, category, difficulty,
languages, description) is embedded. The full body of each challenge — source,
writeups, files — is stored verbatim in the `content` JSONB column and is
fetched separately by id via an agent tool (planned). Embedding metadata only
keeps the similarity signal clean and HNSW vectors small.
"""

from __future__ import annotations

import json
import logging
import os
import random
import time
from collections import deque
from pathlib import Path

import numpy as np
import psycopg
from dotenv import load_dotenv
from google import genai
from pgvector.psycopg import register_vector
from psycopg import sql
from psycopg.conninfo import make_conninfo

from orchestrator.rag_config import EMBEDDING_DIM

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

DATA_DIR = Path(__file__).resolve().parent.parent / "dataset" / "formated_rag_data"
MODEL_ID = os.getenv("EMBEDDING_MODEL", "gemini-embedding-001")

# Gemini's free-tier embedding endpoint allows 100 requests per rolling
# 60-second window. We stay safely under that with a sliding-window
# throttle — see _throttle_embedding_call().
EMBEDDING_RATE_LIMIT = 100
EMBEDDING_WINDOW_SECONDS = 60.0
_embedding_call_times: deque[float] = deque(maxlen=EMBEDDING_RATE_LIMIT)

logger = logging.getLogger(__name__)


class EmbeddingError(RuntimeError):
    """Raised when the embedding provider returns an unusable response."""


def _throttle_embedding_call() -> None:
    """Block until calling _embed won't exceed Gemini's per-minute quota.

    Tracks call timestamps in a bounded deque; if the window already holds
    `EMBEDDING_RATE_LIMIT` calls, sleep until the oldest one ages out.
    """
    now = time.monotonic()
    if len(_embedding_call_times) >= EMBEDDING_RATE_LIMIT:
        wait = EMBEDDING_WINDOW_SECONDS - (now - _embedding_call_times[0])
        if wait > 0:
            logger.info("Embedding throttle: sleeping %.1fs", wait)
            time.sleep(wait)
    _embedding_call_times.append(time.monotonic())


def _get_client() -> genai.Client:
    return genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


def _get_conninfo() -> str:
    try:
        password = os.environ["DB_PASSWORD"]
    except KeyError as e:
        raise RuntimeError(
            "DB_PASSWORD is required for indexing. Set it in .env or the environment."
        ) from e
    return make_conninfo(
        dbname=os.getenv("DB_NAME", "vectordb"),
        user=os.getenv("DB_USER", "admin"),
        password=password,
        host=os.getenv("DB_HOST", "localhost"),
        port=os.getenv("DB_PORT", "5432"),
        connect_timeout="10",
    )


def _check_legacy_schema(conn: psycopg.Connection) -> None:
    """Refuse to operate on a v1 (`uid`-column) `challenges` table.

    The v2 schema generates `id` server-side and dropped the JSON-supplied
    `uid` column. Because `_ensure_schema` uses CREATE TABLE IF NOT EXISTS,
    a v1 table would survive the call unchanged — then INSERT would fail
    with a NOT NULL violation on `uid` and ON CONFLICT (name) would error
    because the v1 table doesn't have a UNIQUE constraint on `name`. Detect
    that case early and tell the operator how to recover.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'challenges' AND column_name = 'uid'
            """
        )
        if cur.fetchone() is not None:
            raise RuntimeError(
                "Legacy v1 schema detected: `challenges.uid` column exists. "
                "The indexer now generates IDs server-side and no longer supplies `uid`, "
                "so re-running against this DB would fail at INSERT time. "
                "Run `DROP TABLE challenges;` (data loss — back up first if needed) "
                "and reindex from scratch."
            )


def _ensure_schema(conn: psycopg.Connection) -> None:
    with conn.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
        # `id` is generated by Postgres on insert; the indexer never supplies
        # one. `name` carries the unique constraint that powers upsert
        # idempotency (re-indexing the same challenge updates the row in
        # place; ON CONFLICT (name) preserves the existing id so agents that
        # cached an id still resolve to the same challenge).
        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS challenges (
                    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                    name        TEXT NOT NULL UNIQUE,
                    description TEXT,
                    category    TEXT,
                    difficulty  INT,
                    languages   TEXT[] NOT NULL DEFAULT '{{}}',
                    content     JSONB,
                    embedding   vector({dim}),
                    indexed_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            ).format(dim=sql.Literal(EMBEDDING_DIM))
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS challenges_embedding_hnsw_idx
            ON challenges USING hnsw (embedding vector_cosine_ops)
            """
        )
        conn.commit()


def _embed(client: genai.Client, text: str, max_429_retries: int = 3) -> np.ndarray:
    """Embed text via Gemini.

    Raises EmbeddingError on empty / malformed responses. Sleeps if the local
    sliding window has hit the rate limit. On a 429 from the API (which can
    fire even when our local counter is under the limit, because other
    processes on the same key share the quota), parses the `retryDelay` from
    the error body and retries up to `max_429_retries` times.
    """
    from google.genai import errors as genai_errors

    for attempt in range(max_429_retries + 1):
        _throttle_embedding_call()
        try:
            result = client.models.embed_content(
                model=MODEL_ID,
                contents=text,
                config={"output_dimensionality": EMBEDDING_DIM},
            )
            break
        except genai_errors.APIError as e:
            if attempt == max_429_retries or getattr(e, "code", None) != 429:
                raise
            # Parse the retryDelay hint out of the error body; default to 30s.
            # Only "<float>s" is parsed — any other unit (e.g. "1m") trips
            # ValueError below and falls back to the 30s default, which is
            # the safe direction (waiting longer than required, not shorter).
            wait = 30.0
            try:
                for detail in (e.details or {}).get("error", {}).get("details", []):
                    if detail.get("@type", "").endswith("RetryInfo"):
                        raw = detail.get("retryDelay", "30s")
                        wait = float(raw.rstrip("s"))
                        break
            except (AttributeError, TypeError, ValueError):
                pass
            # Jitter prevents multiple workers sharing a key from converging
            # on the same retry instant and immediately re-colliding.
            jitter = random.uniform(0, 2)
            logger.warning(
                "Embedding 429; retry %d/%d after %.1fs (+%.1fs jitter)",
                attempt + 1, max_429_retries, wait, jitter,
            )
            time.sleep(wait + 1.0 + jitter)  # +1s safety margin, +jitter for thundering-herd
    if not result.embeddings:
        raise EmbeddingError("Embedding provider returned no embeddings")
    values = result.embeddings[0].values
    if values is None or len(values) != EMBEDDING_DIM:
        raise EmbeddingError(
            f"Embedding provider returned wrong shape: "
            f"got len={len(values) if values is not None else 'None'}, expected {EMBEDDING_DIM}"
        )
    return np.array(values)


def _sanitize_jsonb(item: dict) -> str:
    """Serialize a challenge dict for the JSONB column, stripping characters
    Postgres rejects (specifically `\\u0000` — the JSON spec allows it but
    Postgres TEXT/JSONB doesn't).
    """
    return json.dumps(item, ensure_ascii=False).replace("\\u0000", "")


def _index_one(client: genai.Client, conn: psycopg.Connection, item: dict) -> None:
    # Parent-document pattern: embed metadata only, store full body verbatim
    # in `content` JSONB. The retrieval signal is the metadata; agents fetch
    # the body on demand via id. See module docstring for rationale.
    #
    # `id` is generated server-side by Postgres on first insert. We never
    # supply it; on conflict we preserve the existing id via ON CONFLICT
    # (name), so re-indexing keeps a challenge's id stable.
    name = item.get("task_name", "")
    if not name:
        raise ValueError("challenge JSON is missing 'task_name' — required for upsert")
    category = item.get("category", "")
    # Some dataset entries carry difficulty as a string like "unknown" — coerce
    # those to 0 rather than failing the whole row. A separate data-cleanup
    # task can normalize the dataset.
    raw_difficulty = item.get("difficulty", 0)
    try:
        difficulty = int(raw_difficulty)
    except (TypeError, ValueError):
        logger.warning("Non-integer difficulty %r for %r; storing as 0", raw_difficulty, item.get("task_name"))
        difficulty = 0
    description = item.get("description", "")
    languages = item.get("languages", []) or []

    embed_text = (
        f"name: {name} | "
        f"category: {category} | "
        f"difficulty: {difficulty} | "
        f"languages: {', '.join(languages)} | "
        f"description: {description}"
    )
    vector = _embed(client, embed_text)

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO challenges
                (name, description, category, difficulty, languages, content, embedding, indexed_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT (name) DO UPDATE SET
                description = EXCLUDED.description,
                category    = EXCLUDED.category,
                difficulty  = EXCLUDED.difficulty,
                languages   = EXCLUDED.languages,
                content     = EXCLUDED.content,
                embedding   = EXCLUDED.embedding,
                indexed_at  = CURRENT_TIMESTAMP
            """,
            (name, description, category, difficulty, languages, _sanitize_jsonb(item), vector),
        )
    conn.commit()
    logger.info("Indexed: %s (%s, difficulty %d, languages %s)", name, category, difficulty, languages)


def index_file(client: genai.Client, conn: psycopg.Connection, path: Path) -> None:
    with open(path) as f:
        doc = json.load(f)
    items = doc if isinstance(doc, list) else [doc]
    for item in items:
        _index_one(client, conn, item)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    client = _get_client()
    with psycopg.connect(_get_conninfo()) as conn:
        # The vector extension must exist BEFORE register_vector, which looks
        # up the type OID at registration time. Splitting this out of
        # _ensure_schema lets us run it first; _ensure_schema's own
        # CREATE EXTENSION IF NOT EXISTS is then a no-op.
        with conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
        conn.commit()
        register_vector(conn)
        _check_legacy_schema(conn)
        _ensure_schema(conn)
        failures: list[tuple[Path, Exception]] = []
        for path in sorted(DATA_DIR.glob("*.json")):
            try:
                index_file(client, conn, path)
            except Exception as e:
                # Keep going so one bad JSON doesn't kill the whole reindex.
                # rollback() is required: a failed INSERT leaves the
                # connection in aborted-transaction state, and every
                # subsequent execute() raises InFailedSqlTransaction until
                # the transaction is closed.
                conn.rollback()
                logger.exception("Failed to index %s", path)
                failures.append((path, e))
        if failures:
            logger.error(
                "%d file(s) failed to index: %s",
                len(failures),
                ", ".join(p.name for p, _ in failures),
            )


if __name__ == "__main__":
    main()
