import asyncio
import io
import zipfile
from datetime import datetime
from typing import Dict, List, Optional
from uuid import uuid4

from api.schemas import (
    ArtifactEntry,
    LogEntry,
    RunDetail,
    RunSummary,
    StageStatus,
    ValidationResult,
)


class OrchestratorService:
    def __init__(self):
        # very small in-memory store for runs
        self.runs: Dict[str, Dict] = {}

    def start_run(self, prompt: dict) -> str:
        run_id = f"r-{uuid4().hex[:8]}"
        now = datetime.utcnow()
        stages = [
            StageStatus(name=s, status='queued') for s in
            ('Architect', 'Storyteller', 'Developer', 'DevOps', 'Solver', 'Validator')
        ]
        self.runs[run_id] = {
            'summary': RunSummary(run_id=run_id, prompt=prompt, status='pending', started_at=now, current_stage=None),
            'stages': stages,
            'artifacts': [],
            'logs': [],
            'validation': None,
        }
        # schedule background simulation
        asyncio.create_task(self._simulate_run(run_id))
        return run_id

    async def _simulate_run(self, run_id: str):
        # simple progression sim
        store = self.runs.get(run_id)
        if not store:
            return
        store['summary'].status = 'running'
        for stage in store['stages']:
            stage.status = 'running'
            store['summary'].current_stage = stage.name
            self._log(run_id, 'info', f"{stage.name} started")
            await asyncio.sleep(0.5)
            # create fake artifact for developer
            if stage.name == 'Developer':
                a = ArtifactEntry(path='source/main.c', role='source', agent='Developer', size=1234)
                store['artifacts'].append(a)
                self._log(run_id, 'info', 'Developer wrote source/main.c')
            stage.status = 'passed'
            stage.finished_at = datetime.utcnow()
            await asyncio.sleep(0.1)
        # validation
        store['validation'] = ValidationResult(passed=True, flag='CTF{simulated_flag}', logs=[])
        store['summary'].status = 'succeeded'
        store['summary'].finished_at = datetime.utcnow()
        self._log(run_id, 'info', 'Run completed')

    def _log(self, run_id: str, level: str, message: str):
        entry = LogEntry(timestamp=datetime.utcnow(), level=level, message=message)
        self.runs[run_id]['logs'].append(entry)

    def get_run(self, run_id: str) -> Optional[RunDetail]:
        r = self.runs.get(run_id)
        if not r:
            return None
        return RunDetail(
            summary=r['summary'],
            stages=r['stages'],
            artifacts=r['artifacts'],
            validation=r.get('validation'),
        )

    def list_runs(self, limit: int = 50, offset: int = 0) -> List[RunSummary]:
        items = [v['summary'] for v in self.runs.values()]
        return items[offset: offset + limit]

    def cancel_run(self, run_id: str) -> bool:
        r = self.runs.get(run_id)
        if not r:
            return False
        r['summary'].status = 'cancelled'
        self._log(run_id, 'info', 'Cancelled by user')
        return True

    def retry_run(self, run_id: str) -> Optional[str]:
        # create a new run copying prompt
        r = self.runs.get(run_id)
        if not r:
            return None
        return self.start_run(r['summary'].prompt.dict() if hasattr(r['summary'].prompt, 'dict') else r['summary'].prompt)

    def list_artifacts(self, run_id: str) -> List[ArtifactEntry]:
        r = self.runs.get(run_id)
        if not r:
            return []
        return r['artifacts']

    def emit_event(self, run_id: str, event: dict):
        # debug helper: push event into logs
        self._log(run_id, 'debug', f"user-event: {event}")

    def download_run_zip(self, run_id: str) -> bytes:
        r = self.runs.get(run_id)
        if not r:
            raise FileNotFoundError()
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, 'w') as z:
            # include fake files
            for a in r['artifacts']:
                z.writestr(a.path, f"// generated by {a.agent} (size={a.size})\n")
            z.writestr('README.md', f"Run: {run_id}\nStatus: {r['summary'].status}\n")
        buf.seek(0)
        return buf.read()


orchestrator_service = OrchestratorService()
